---
params:
  region:
    choices:
    - East North Central
    - South Atlantic
    - New England
    - Middle Atlantic
    - West South Central
    - West North Central
    - Pacific
    - Mountain
    - East South Central
    input: select
    label: 'Region:'
    value: Mountain
author: "Raja Muthuraman"
date: "29 March 2019"
output:
  ioslides_presentation:
    logo: images/sunstar.png
title: "Weather Information Preferences"
subtitle: Summary Report for `r params$region` Report

---

```{r, echo=FALSE, message=FALSE, warning=FALSE}
knitr::read_chunk("code/setup.R")
```

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
```

```{r loadData}

```


```{r child="text/backgroundsection.Rmd"}

```

```{r child="text/purposesection.Rmd"}

```


## Demographic Summary Tables


respondents were:

```{r makeTable, code=readLines("code/makeTable.R")}


```


## Weather Source Preference by Gender

Finally, here is a breakdown of the `r nrow(sdat)` survey respondents for the `r params$region` region of the US on how they check their daily weather by gender.
```{r}
knitr::read_chunk("code/makechart.R")

```

```{r makeCharts}

```

